Feat/add types,weights,cargo permission
froozy3/RoadTrafficApp pull request #3
Opened 2024-03-06 15:24 UTC by froozy3

2024-03-06 17:12 UTC, TaranenkoDenis requested changes

2024-03-06 17:12 UTC, TaranenkoDenis commented on src/input_generator/data/Transport.java
> +    public final String type;
`TransportType` not `String`

2024-03-06 17:12 UTC, TaranenkoDenis commented on src/input_generator/data/Transport.java
> +    public final String weight;
`int` not `String`

2024-03-06 17:12 UTC, TaranenkoDenis commented on src/input_generator/data/Transport.java
>      public final String speed;
`int` not `String`

2024-03-06 17:12 UTC, TaranenkoDenis commented on src/input_generator/data/Transport.java
>      public final String direction;
Here should something like `public final bool rightDirection;`

2024-03-06 17:12 UTC, TaranenkoDenis commented on src/input_generator/data/Transport.java
> +    public Transport(String type, String weight, String color, String engine, float cargoPermission, String cargo, String speed, String direction) {
The same here, types should be as types of the variables inside class.

2024-03-06 17:12 UTC, TaranenkoDenis commented on src/input_generator/InputGenerator.java
> +                    0.8f,
You should generate boolean value from 0.8f probability.

2024-03-07 12:51 UTC, froozy3 commented on src/input_generator/data/TransportTypeDescription.java
> +    public TransportType getType() {
I make this getter for convertTypesToMap 
![Без имени](https://github.com/froozy3/RoadTrafficApp/assets/161760611/89ee2627-f734-4ea7-b2f5-959386e8121a)

2024-03-07 13:28 UTC, TaranenkoDenis commented on src/input_generator/data/TransportTypeDescription.java
> +    public TransportType getType() {
1. In this case you can make these fields `public`, since they are `final` and remove getters. 
2. You should put to the `HashMap` `TransportType`, not `String`.

2024-03-07 13:28 UTC, TaranenkoDenis commented on src/input_generator/data/Weight.java
> +    public int getMin() {
The same here. I don't understand why you use getters for the `public final` fields.

2024-03-07 13:28 UTC, TaranenkoDenis commented on src/input_generator/data/TransportTypeDescription.java
> +        return probability;
The same with probability, you can just make the field `public`.

2024-03-07 13:28 UTC, TaranenkoDenis commented on src/input_generator/data/TransportTypeDescription.java
> +        return probability;
Read more about when you should use `public` and `private` modificators.

2024-03-07 13:53 UTC, froozy3 commented on src/input_generator/data/Weight.java
> +    public int getMin() {
Beacause, im stupid

2024-03-07 22:05 UTC, closed without merging